### ISSUE TITLE
CDR Sandbox ENVAUOB(/token API Failure)

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#18]
Hi @CDR-DavidR,

We are facing issue to read the response for the /token call from one of our lower environments where max response wait time is 3secs. As per the logs, we can see that token call is taking more 6secs(assuming ElapsedTime is in miliseconds). Could you please check and confirm us on why this is taking more time here. Attached the logs for debugging.

Failure Stack at our end: {"errorCode":"io_error","errorMessage":"failed or interrupted I/O operations for end site while connecting url : https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token : java.net.SocketTimeoutException: Read timed out\n\tat java.base/java.net.SocketInputStream.socketRead0

Regards - Puneet sharma
[sb-logfile-20221130-131256.csv](https://github.com/ConsumerDataRight/sandbox/files/10125528/sb-logfile-20221130-131256.csv)

**Comment by psharma211** [comment]
@CDR-DavidR  can you please review and help us to find the issue

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

Thank you for raising this issue. We are investigating and can see that some calls are taking longer than expected. The current percentage of calls to the Sandbox Banking Data Holder within the last five days that cross a 3 second elapsed time is relatively low at 0.03%.

There are a number of automated maintenance tasks running in the Sandbox which is the most likely cause of a slow down in performance. It does not look like the cause would be due to the request being received. We will continue to investigate further to see if we can pinpoint the root cause.

**Comment by psharma211** [comment]
thank you @CDR-AndrewG for update. Please investigate and let us know if you find anything. we are still facing same issue at our end.

**Comment by psharma211** [comment]
@CDR-AndrewG @CDR-DavidR can you please share an update on this. we are blocked in testing due to this issue.

**Comment by psharma211** [comment]
Hi, @CDR-AndrewG @CDR-DavidR  please help on this to unblock our testing. we are currently in a blocked state.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

The root cause of this issue has now been identified. Our upcoming release should address this issue.

**Comment by psharma211** [comment]
@CDR-AndrewG @CDR-DavidR  do we have any update on this and please share some ETA

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

Deployment of our next release will be within the next two weeks.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

Our latest release was completed yesterday. Let us know if you are still experiencing this issue.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

Please reach out again if you experience any further issues.
